/* Copyright 2026 上海如静知华信息科技有限公司 · https://www.zhuatech.cn/ */
package cn.zhuatech.helpdesk;
import org.junit.jupiter.api.Test;import org.springframework.beans.factory.annotation.Autowired;import org.springframework.boot.test.context.SpringBootTest;import org.springframework.boot.webmvc.test.autoconfigure.AutoConfigureMockMvc;import org.springframework.http.MediaType;import org.springframework.test.web.servlet.*;import java.time.LocalDateTime;import java.util.regex.Pattern;
import static org.springframework.security.test.web.servlet.request.SecurityMockMvcRequestPostProcessors.httpBasic;import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.*;import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.*;
@SpringBootTest @AutoConfigureMockMvc class HelpdeskCoreApiTests{@Autowired MockMvc mvc;
 @Test void ticketRunsThroughAssignmentResponseResolutionCloseAndReopen()throws Exception{long id=create("HD-CORE-1",LocalDateTime.now());post(id,"assign","{\"team\":\"应用支持\",\"assignee\":\"张工\"}").andExpect(jsonPath("$.data.status").value("ASSIGNED"));post(id,"respond",remark("已开始排查")).andExpect(jsonPath("$.data.status").value("IN_PROGRESS"));post(id,"resolve","{\"resolution\":\"清理缓存并恢复服务\"}").andExpect(jsonPath("$.data.status").value("RESOLVED"));post(id,"close",remark("用户确认")).andExpect(jsonPath("$.data.status").value("CLOSED"));post(id,"reopen",remark("问题复现")).andExpect(jsonPath("$.data.reopenCount").value(1));}
 @Test void ticketCannotResolveBeforeAssignmentAndResponse()throws Exception{long id=create("HD-CORE-2",LocalDateTime.now());post(id,"resolve","{\"resolution\":\"直接关闭\"}").andExpect(status().isConflict());}
 @Test void waitingCustomerPausesAndResumesSla()throws Exception{long id=create("HD-CORE-3",LocalDateTime.now());post(id,"assign","{\"team\":\"一线\",\"assignee\":\"李工\"}");post(id,"respond",remark("已响应"));post(id,"wait-customer",remark("等待日志")).andExpect(jsonPath("$.data.status").value("WAITING_CUSTOMER"));post(id,"resume",remark("客户已提供")).andExpect(jsonPath("$.data.status").value("IN_PROGRESS"));}
 @Test void slaSummaryDetectsHistoricalBreaches()throws Exception{create("HD-CORE-4",LocalDateTime.now().minusDays(1));mvc.perform(get("/api/core/helpdesk/sla-summary").with(httpBasic("operator","operator123"))).andExpect(status().isOk()).andExpect(jsonPath("$.data.responseBreached").isNumber()).andExpect(jsonPath("$.data.resolutionBreached").isNumber());}
 @Test void ticketCoreRequiresAuthentication()throws Exception{mvc.perform(get("/api/core/helpdesk/tickets")).andExpect(status().isUnauthorized());}
 private long create(String no,LocalDateTime reported)throws Exception{MvcResult r=mvc.perform(org.springframework.test.web.servlet.request.MockMvcRequestBuilders.post("/api/core/helpdesk/tickets").with(httpBasic("operator","operator123")).contentType(MediaType.APPLICATION_JSON).content("{\"ticketNo\":\""+no+"\",\"requester\":\"华东客户\",\"category\":\"应用故障\",\"priority\":\"P1\",\"subject\":\"核心业务异常\",\"reportedAt\":\""+reported+"\",\"responseSlaMinutes\":15,\"resolutionSlaMinutes\":120}")).andExpect(status().isOk()).andReturn();var m=Pattern.compile("\\\"id\\\":(\\d+)").matcher(r.getResponse().getContentAsString());m.find();return Long.parseLong(m.group(1));}
 private ResultActions post(long id,String action,String body)throws Exception{return mvc.perform(org.springframework.test.web.servlet.request.MockMvcRequestBuilders.post("/api/core/helpdesk/tickets/"+id+"/"+action).with(httpBasic("operator","operator123")).contentType(MediaType.APPLICATION_JSON).content(body));}
 private String remark(String value){return "{\"remark\":\""+value+"\"}";}
}
